// 01）空间侧栏折叠动画时长（PROFILE_SPACE_SIDEBAR_COLLAPSE_DURATION_MS）
export const PROFILE_SPACE_SIDEBAR_COLLAPSE_DURATION_MS = 280

// 02）个人空间主页预览条数（PROFILE_SPACE_PERSONAL_HOME_*）
export const PROFILE_SPACE_PERSONAL_HOME_PROJECT_PREVIEW_LIMIT = 3
export const PROFILE_SPACE_PERSONAL_HOME_NOTE_PREVIEW_LIMIT = 4

// 03）团队空间主页预览条数（PROFILE_SPACE_TEAM_HOME_*）
export const PROFILE_SPACE_TEAM_HOME_PROJECT_PREVIEW_LIMIT = 3
export const PROFILE_SPACE_TEAM_HOME_NOTE_PREVIEW_LIMIT = 3
export const PROFILE_SPACE_TEAM_HOME_ACHIEVEMENT_PREVIEW_LIMIT = 3

// 04）机构空间主页预览条数（PROFILE_SPACE_ORG_HOME_*）
export const PROFILE_SPACE_ORG_HOME_PROJECT_PREVIEW_LIMIT = 3
export const PROFILE_SPACE_ORG_HOME_NOTE_PREVIEW_LIMIT = 3
export const PROFILE_SPACE_ORG_HOME_TEAM_PREVIEW_LIMIT = 4
export const PROFILE_SPACE_ORG_HOME_MEMBER_PREVIEW_LIMIT = 8

// 05）成员网格预览（PROFILE_SPACE_MEMBERS_PREVIEW_*）
export const PROFILE_SPACE_MEMBERS_PREVIEW_MAX_ROWS = 2
export const PROFILE_SPACE_MEMBER_CARD_HEIGHT_PX = 72
