import type { Announcement, ProjectItem, RecommendedCompany } from '../../types/project'
import type { ProfileNoteItem } from '../ProfileSpace/components/types'

// 01）首页项目卡片数据（homePageProjects）
export const homePageProjects: ProjectItem[] = [
  {
    uid: 'PR00000001001',
    title: '基于大模型的智能问答系统开发',
    preview: '构建企业级智能问答平台，支持多知识库接入与权限管理，提升内部知识检索效率。',
    tags: [{ label: 'AI开发' }, { label: '后端管理' }, { label: 'Python' }, { label: '大模型' }],
    category: 'COMMERCIAL',
    ownerOrganization: '智源科技有限公司',
    publishTime: '2小时前发布',
    level: 'R',
    budget: '28,600',
    teamSize: '3-5人',
    duration: '3个月',
    status: 'OPEN',
  },
  {
    uid: 'PR00000001002',
    title: '校园二手交易平台小程序开发',
    preview: '开发一款面向大学生的二手交易平台小程序，包含发布、搜索、聊天、支付等核心功能。',
    tags: [{ label: '小程序' }, { label: 'JavaScript' }, { label: 'UI设计' }, { label: '微信生态' }],
    category: 'RECRUITMENT',
    recruitmentType: 'TEAM_RECRUIT',
    ownerOrganization: '校园互联创新团队',
    publishTime: '5小时前发布',
    level: 'SR',
    teamSize: '4-8人',
    duration: '2个月',
    status: 'OPEN',
  },
  {
    uid: 'PR00000001003',
    title: '数据可视化大屏设计与开发',
    preview: '为企业管理后台设计数据可视化大屏，整合多源数据，提供直观的业务展示与分析能力。',
    tags: [{ label: '数据可视化' }, { label: 'Vue.js' }, { label: 'ECharts' }, { label: '大屏设计' }],
    category: 'COMMERCIAL',
    ownerOrganization: '数智未来科技',
    publishTime: '1天前发布',
    level: 'SSR',
    budget: '22,400',
    teamSize: '2-4人',
    duration: '1个月',
    status: 'OPEN',
  },
  {
    uid: 'PR00000001004',
    title: '企业官网重构设计',
    preview: '为企业重新设计官网，提升品牌形象与用户体验，支持多终端适配与内容管理。',
    tags: [{ label: 'Web设计' }, { label: '品牌化设计' }, { label: '前端开发' }],
    category: 'RECRUITMENT',
    recruitmentType: 'LAB_RECRUIT',
    ownerOrganization: '创新互联实验室',
    publishTime: '2天前发布',
    level: 'N',
    teamSize: '2-3人',
    duration: '3个月',
    status: 'OPEN',
  },
  {
    uid: 'PR00000001005',
    title: '基于机器学习的销售预测系统',
    preview: '利用机器学习算法构建销售预测模型，帮助企业优化库存与销售策略。',
    tags: [{ label: '机器学习' }, { label: 'Python' }, { label: '数据分析' }, { label: '预测建模' }],
    category: 'RECRUITMENT',
    recruitmentType: 'PERSONAL_RECRUIT',
    ownerOrganization: '睿云数据科技',
    publishTime: '3天前发布',
    level: 'UR',
    teamSize: '1人',
    duration: '4个月',
    status: 'OPEN',
  },
]

// 02）首页推荐项目类型（homePageRecommendedTypes）
export const homePageRecommendedTypes: string[] = [
  'AI',
  'Web开发',
  '小程序',
  '数据分析',
  'UI设计',
  'Python',
  '移动开发',
  '游戏开发',
]

// 03）首页推荐企业（homePageRecommendedCompanies）
export const homePageRecommendedCompanies: RecommendedCompany[] = [
  { name: '智源科技有限公司', projects: '156 个项目在招' },
  { name: '数智未来科技', projects: '128 个项目在招' },
  { name: '跃新互联有限公司', projects: '98 个项目在招' },
  { name: '云创未来科技', projects: '86 个项目在招' },
]

// 04）首页公告（homePageAnnouncements）
export const homePageAnnouncements: Announcement[] = [
  { title: '2024 年度优秀项目评选活动正式启动', date: '05-20' },
  { title: '第六期企业实战项目征集进行中', date: '05-18' },
  { title: '高校合作计划新增 10 所合作院校', date: '05-15' },
  { title: '平台功能升级公告', date: '05-12' },
]

// 05）首页经验推荐笔记（homePageExperienceNotes）
export const homePageExperienceNotes: ProfileNoteItem[] = [
  {
    title: '大模型应用从 Demo 到上线实战',
    summary: '梳理从原型验证到可运营上线的全流程关键点，包含评测、灰度与监控经验。',
    contentType: '图文',
    tags: ['人工智能', '工程实践', '上线流程'],
    publishTime: '2026-05-10 10:20',
    updateTime: '2026-05-10',
    views: 1268,
    comments: 88,
    favorites: 203,
    cover: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=600&q=80',
    authorName: '李学长',
    authorOrganization: '清华大学',
  },
  {
    title: '前端性能优化 Checklist（校园项目版）',
    summary: '覆盖首屏优化、资源加载、缓存策略与监控埋点，适合课程与竞赛项目快速落地。',
    contentType: '图文',
    tags: ['前端开发', '性能优化', 'Checklist'],
    publishTime: '2026-05-08 15:35',
    updateTime: '2026-05-08',
    views: 942,
    comments: 57,
    favorites: 146,
    cover: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=600&q=80',
  },
  {
    title: '高质量项目汇报 PPT 设计模板',
    summary: '从结构、叙事与视觉规范三个层面拆解项目汇报模板，提升表达效率与专业度。',
    contentType: '图文',
    tags: ['平面设计', '汇报表达', '模板'],
    publishTime: '2026-05-06 20:10',
    updateTime: '2026-05-06',
    views: 713,
    comments: 31,
    favorites: 109,
    cover: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=600&q=80',
  },
  {
    title: '校企项目沟通术：需求确认到结项复盘',
    summary: '总结校企协作中常见沟通误区，提供从需求对齐到验收复盘的可执行方法。',
    contentType: '视频',
    tags: ['项目管理', '沟通协作', '结项复盘'],
    publishTime: '2026-05-04 18:05',
    updateTime: '2026-05-04',
    views: 856,
    comments: 49,
    favorites: 121,
    cover: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80',
    authorName: '王老师',
    authorOrganization: '深圳技术大学',
    videoDuration: '08:16',
  },
  {
    title: '高校开发团队协作规范落地手册',
    summary: '从 Git 分支策略到 Code Review 清单，建立适合学生团队的协作规范体系。',
    contentType: '图文',
    tags: ['团队协作', '工程规范', 'Git'],
    publishTime: '2026-05-02 16:30',
    updateTime: '2026-05-02',
    views: 798,
    comments: 41,
    favorites: 132,
    cover: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80',
  },
  {
    title: '从竞赛到商业化：项目成果转化经验',
    summary: '分享竞赛项目商业化过程中需求重构、用户验证与持续迭代的关键方法。',
    contentType: '图文',
    tags: ['项目孵化', '用户验证', '商业化'],
    publishTime: '2026-04-30 12:45',
    updateTime: '2026-04-30',
    views: 667,
    comments: 35,
    favorites: 118,
    cover: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
  },
  {
    title: 'React 组件设计模式实战笔记',
    summary: '归纳容器/展示分离、复合组件与状态提升等模式，并给出可复用的目录结构建议。',
    contentType: '图文',
    tags: ['React', '组件设计', '前端架构'],
    publishTime: '2026-04-28 09:15',
    updateTime: '2026-04-28',
    views: 584,
    comments: 28,
    favorites: 96,
    cover: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=600&q=80',
  },
  {
    title: '数据库索引优化入门（项目向）',
    summary: '结合真实慢查询案例，讲解索引选择、覆盖索引与执行计划分析的基本方法。',
    contentType: '视频',
    tags: ['数据库', '性能优化', 'MySQL'],
    publishTime: '2026-04-26 14:50',
    updateTime: '2026-04-26',
    views: 521,
    comments: 22,
    favorites: 87,
    cover: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=600&q=80',
  },
]
